spring:
  ### DB Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/biginsight?useUnicode=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: wodus123

  ### JPA Config
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect